# Generated by Django 5.2.5 on 2025-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tital',
            new_name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
